### ISSUE TITLE
ActionBarSherlock 4.1.0 has been released

### ISSUE THREAD

**Issue by candrews** [rtyley/roboguice-sherlock#10]
ActionBarSherlock 4.1.0 has been released. You should probably bump the dependency version in your pom.xml, and test against it to make sure everything still works okay.

Thanks!

**Comment by rtyley** [comment]
I'm currently testing Agit against ABS 4.1.0, looks good there, though obviously that doesn't exercise all ABS functionality.

I'm not intending to release a version-bump of roboguice-sherlock on this version of ABS tho, unless you know of a specific issue that makes that necessary? Users who want to upgrade can simply update the poms of their own projects with the specific ABS dependency, rather than waiting for me to push out a redundant release. 

The code in roboguice-sherlock is just code that extends ABS classes, it doesn't duplicate them, and it also doesn't reference any ABS functionality - it just overrides the normal Activity/Fragment method definitions, so there's limited potential for an ABS upgrade to break things (rather more potential with a roboguice upgrade).

However, if you know of a specific issue that needs addressing, please let me know and we can get a new release pushed out.

**Comment by JakeWharton** [comment]
The minor version bump was more representative of the significance of a change rather than signifying a large number of changes. Functionally there is almost nothing different from 4.0.2 except moving a few methods to a class in a different package.

**Comment by Wavesonics** [comment]
ABS 4.2.0 has now been released, is there any need for roboguice to update? I'm considering using this lib, but just want to be sure it's being maintained.

**Comment by rtyley** [comment]
I've not yet evaluated roboguice-sherlock against ABS 4.2.0, but as I said above, the code in roboguice-sherlock is just code that extends ABS classes, it doesn't duplicate them, and it also doesn't reference any ABS functionality - it just overrides the normal Activity/Fragment method definitions with duplication of RoboGuice logic. So there's limited potential for an ABS upgrade to break things (rather more potential with a roboguice upgrade).
