### ISSUE TITLE
@InjectPreference not working with RoboSherlockPreferenceActivity

### ISSUE THREAD

**Issue by jelies** [rtyley/roboguice-sherlock#12]
Hi,

I was trying to inject a preference with `@InjectPreference` in a RoboSherlockPreferenceActivity and it was not working, an `EmptyStackException` was thrown internally on Roboguice code. So, I decided to try with `RoboPreferenceActivity` (without ABS), and `@InjectPreferences` was working fine. Checking code of `RoboSherlockPreferenceActivity.setPreferenceScreen()` against `RoboPreferenceActivity.setPreferenceScreen()` I noticed some differences. 

Using these lines (exactly the ones in `RoboPreferenceActivity`):

```
@Override
public void setPreferenceScreen(PreferenceScreen preferenceScreen) {
    super.setPreferenceScreen(preferenceScreen);

    // Lines added 
    final ContextScope scope = RoboGuice.getInjector(this).getInstance(ContextScope.class);
    synchronized (ContextScope.class) {
        scope.enter(this);
        try {
            preferenceListener.injectPreferenceViews();
        } finally {
            scope.exit(this);
        }
    }
}
```

instead of these:

```
@Override
public void setPreferenceScreen(PreferenceScreen preferenceScreen) {
    super.setPreferenceScreen(preferenceScreen);
    preferenceListener.injectPreferenceViews();
}
```

Makes `@InjectPreference` to work fine.

Thanks a lot for all your work guys!!

Cheers,

Jordi.

P.S.: This is happening in 1.4 version and in last 1.5-SNAPSHOT. Currently using ABS 4.1.0 and RoboGuice 2.0.

**Comment by rtyley** [comment]
Thanks @jelies - you're completely right, looks like the initial commit of RoboSherlockPreferenceActivity didn't have those lines:

https://github.com/rtyley/roboguice-sherlock/blob/94ff9aa815c360bc46cca5b4053b058f35bfe5c0/src/main/java/com/github/rtyley/android/sherlock/roboguice/activity/RoboSherlockPreferenceActivity.java#L63-67

...because it was based on the then-current version of RoboGuice, which didn't have them either:

http://code.google.com/p/roboguice/source/browse/roboguice/src/main/java/roboguice/activity/RoboPreferenceActivity.java?spec=svn2a436cd54a22b433d4dbef4b9170ac39472f66c4&r=2a436cd54a22b433d4dbef4b9170ac39472f66c4

I'll look into fixing this up, unless you'd like to submit a pull request to do that?

**Comment by rtyley** [comment]
The new 1.5 release contains this fix, and has been promoted to Maven Central - thanks for reporting the issue!

http://search.maven.org/#artifactdetails%7Ccom.github.rtyley%7Croboguice-sherlock%7C1.5%7Cjar

**Comment by jelies** [comment]
Great! Issue solved and new version on maven central! Thanks to you @rtyley! :)
